In [1]:
import pandas as pd

In [20]:
df = pd.read_csv("airbnb.csv")
df.head()

,id_visitor,id_session,dim_session_number,dim_user_agent,dim_device_app_combo,ds,ts_min,ts_max,did_search,sent_message,...,next_id_session,next_dim_session_number,next_dim_user_agent,next_dim_device_app_combo,next_ds,next_ts_min,next_ts_max,next_did_search,next_sent_message,next_sent_booking_request
0,ed1329a6-064d-47e9-93bc-93f5a50822df,a8dfb8ed5aa79e00ff14b2da297c9778,83,Airbnb/6.0 iPhone/8.1.2,iPhone - iOS,2015-02-16,2015-02-16 21:50:41,2015-02-16 22:13:42,0,0,...,b812bf56bf89b0b31f4e5b50d0c15ff8,84.0,Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKi...,Desktop - Chrome,2015-02-18,2015-02-18 11:57:15,2015-02-18 12:12:48,0.0,0.0,0.0
1,ed1329a6-064d-47e9-93bc-93f5a50822df,950277daef16f86dc2c05d2b212eea81,84,Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKi...,Desktop - Chrome,2015-02-18,2015-02-18 11:57:15,2015-02-18 12:12:48,0,0,...,456083b5f5506ad125d595006819de1d,85.0,Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKi...,Desktop - Chrome,2015-02-18,2015-02-18 13:02:13,2015-02-18 13:05:36,0.0,0.0,0.0
2,ed1329a6-064d-47e9-93bc-93f5a50822df,ee4e2f99dd0c0bef2d40e4bdf880c862,85,Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKi...,Desktop - Chrome,2015-02-18,2015-02-18 13:02:13,2015-02-18 13:05:36,0,0,...,94d30e9f3c8f92ae691e49d77a884777,86.0,Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKi...,Desktop - Chrome,2015-02-18,2015-02-18 14:18:17,2015-02-18 14:28:47,0.0,0.0,0.0
3,ed1329a6-064d-47e9-93bc-93f5a50822df,59fbde7b5d35403116c461fa7fc1ab6e,86,Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKi...,Desktop - Chrome,2015-02-18,2015-02-18 14:18:17,2015-02-18 14:28:47,0,0,...,ab02139dc81bea4b126cf5043faf53d9,87.0,Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKi...,Desktop - Chrome,2015-02-19,2015-02-19 12:24:57,2015-02-19 12:24:59,0.0,0.0,0.0
4,ed1329a6-064d-47e9-93bc-93f5a50822df,ec8972a3c7256ea4dcba61ee2bd9e3a8,87,Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKi...,Desktop - Chrome,2015-02-19,2015-02-19 12:24:57,2015-02-19 12:24:59,0,0,...,6a69db1a5876e9798947f20e2c52bcc8,88.0,Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKi...,Desktop - Chrome,2015-02-19,2015-02-19 22:21:58,2015-02-19 22:22:02,0.0,0.0,0.0

In [21]:
columns_i_want = ["ds", "id_session", "dim_device_app_combo", "did_search", "sent_message"]
new_df = df[columns_i_want]

In [22]:
new_df.head()

,ds,id_session,dim_device_app_combo,did_search,sent_message
0,2015-02-16,a8dfb8ed5aa79e00ff14b2da297c9778,iPhone - iOS,0,0
1,2015-02-18,950277daef16f86dc2c05d2b212eea81,Desktop - Chrome,0,0
2,2015-02-18,ee4e2f99dd0c0bef2d40e4bdf880c862,Desktop - Chrome,0,0
3,2015-02-18,59fbde7b5d35403116c461fa7fc1ab6e,Desktop - Chrome,0,0
4,2015-02-19,ec8972a3c7256ea4dcba61ee2bd9e3a8,Desktop - Chrome,0,0

In [23]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7756 entries, 0 to 7755
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   ds                    7756 non-null   object
 1   id_session            7756 non-null   object
 2   dim_device_app_combo  7756 non-null   object
 3   did_search            7756 non-null   int64
 4   sent_message          7756 non-null   int64
dtypes: int64(2), object(3)
memory usage: 303.1+ KB

In [24]:
new_df['ds'] = pd.to_datetime(new_df['ds'], format="mixed")

C:\Users\SourceBird\AppData\Local\Temp\ipykernel_12308\2526599784.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['ds'] = pd.to_datetime(new_df['ds'], format="mixed")

In [25]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7756 entries, 0 to 7755
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   ds                    7756 non-null   datetime64[ns]
 1   id_session            7756 non-null   object
 2   dim_device_app_combo  7756 non-null   object
 3   did_search            7756 non-null   int64
 4   sent_message          7756 non-null   int64
dtypes: datetime64[ns](1), int64(2), object(2)
memory usage: 303.1+ KB

In [26]:
new_df['did_search'].unique()

array([0, 1])

In [30]:
unique = set()
for i in new_df['did_search'].values:
    unique.add(int(i))

print(unique)

{0, 1}

In [28]:
new_df.loc[0, 'did_search'] = 1

In [29]:
new_df.head()

,ds,id_session,dim_device_app_combo,did_search,sent_message
0,2015-02-16,a8dfb8ed5aa79e00ff14b2da297c9778,iPhone - iOS,1,0
1,2015-02-18,950277daef16f86dc2c05d2b212eea81,Desktop - Chrome,0,0
2,2015-02-18,ee4e2f99dd0c0bef2d40e4bdf880c862,Desktop - Chrome,0,0
3,2015-02-18,59fbde7b5d35403116c461fa7fc1ab6e,Desktop - Chrome,0,0
4,2015-02-19,ec8972a3c7256ea4dcba61ee2bd9e3a8,Desktop - Chrome,0,0

In [35]:
from random import choice
newColList = []
for _ in new_df.index:
    newColList.append(choice(range(0, 100)))
new_df['random'] = newColList
new_df.head()

C:\Users\SourceBird\AppData\Local\Temp\ipykernel_12308\105790037.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['random'] = newColList

,ds,id_session,dim_device_app_combo,did_search,sent_message,random
0,2015-02-16,a8dfb8ed5aa79e00ff14b2da297c9778,iPhone - iOS,1,0,68
1,2015-02-18,950277daef16f86dc2c05d2b212eea81,Desktop - Chrome,0,0,31
2,2015-02-18,ee4e2f99dd0c0bef2d40e4bdf880c862,Desktop - Chrome,0,0,61
3,2015-02-18,59fbde7b5d35403116c461fa7fc1ab6e,Desktop - Chrome,0,0,91
4,2015-02-19,ec8972a3c7256ea4dcba61ee2bd9e3a8,Desktop - Chrome,0,0,32

In [41]:
print(
    sorted(
        new_df['random'].unique()
    )
)

[np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12), np.int64(13), np.int64(14), np.int64(15), np.int64(16), np.int64(17), np.int64(18), np.int64(19), np.int64(20), np.int64(21), np.int64(22), np.int64(23), np.int64(24), np.int64(25), np.int64(26), np.int64(27), np.int64(28), np.int64(29), np.int64(30), np.int64(31), np.int64(32), np.int64(33), np.int64(34), np.int64(35), np.int64(36), np.int64(37), np.int64(38), np.int64(39), np.int64(40), np.int64(41), np.int64(42), np.int64(43), np.int64(44), np.int64(45), np.int64(46), np.int64(47), np.int64(48), np.int64(49), np.int64(50), np.int64(51), np.int64(52), np.int64(53), np.int64(54), np.int64(55), np.int64(56), np.int64(57), np.int64(58), np.int64(59), np.int64(60), np.int64(61), np.int64(62), np.int64(63), np.int64(64), np.int64(65), np.int64(66), np.int64(67), np.int64(68), np.int64(69), np.int64(70), np.int64(71), np.int64(72), np.int64(73), np.int64(74), np.int64(75), np.int64(76), np.int64(77), np.int64(78), np.int64(79), np.int64(80), np.int64(81), np.int64(82), np.int64(83), np.int64(84), np.int64(85), np.int64(86), np.int64(87), np.int64(88), np.int64(89), np.int64(90), np.int64(91), np.int64(92), np.int64(93), np.int64(94), np.int64(95), np.int64(96), np.int64(97), np.int64(98), np.int64(99)]

In [42]:
# any value in random more than 50 should be set to 50

# find out what random is (new_df['random']) and get its values
# create a new variable  to store our result
# use for loop for i in new_df['random'].values
# if i  >= 50: append to an emptylist

if new_df['random'] >= 50 and new_df['random'] <= 100:
   # print

In [47]:
new_list = []
for i in new_df['random'].values:
    #if new_df['random'] >= 50 and new_df['random'] <= 100:
        if i >= 50:
            new_list.append(50)
        else:
            new_list.append(int(i))

In [75]:
new_df.loc[0, 'newlist']

np.int64(50)

In [76]:
new_df.head()

,ds,id_session,dim_device_app_combo,did_search,sent_message,random,newlist,1,new_list
0,2015-02-16,a8dfb8ed5aa79e00ff14b2da297c9778,iPhone - iOS,1,0,68,50,NaN,1.0
1,2015-02-18,950277daef16f86dc2c05d2b212eea81,Desktop - Chrome,0,0,31,31,NaN,NaN
2,2015-02-18,ee4e2f99dd0c0bef2d40e4bdf880c862,Desktop - Chrome,0,0,61,50,NaN,NaN
3,2015-02-18,59fbde7b5d35403116c461fa7fc1ab6e,Desktop - Chrome,0,0,91,50,NaN,NaN
4,2015-02-19,ec8972a3c7256ea4dcba61ee2bd9e3a8,Desktop - Chrome,0,0,32,32,NaN,NaN